// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CheckBimiData, CheckBimiErrors, CheckBimiResponses, CheckBlacklistData, CheckBlacklistErrors, CheckBlacklistResponses, CreateTestData, CreateTestErrors, CreateTestResponses, GetRawEmailData, GetRawEmailErrors, GetRawEmailResponses, GetReportData, GetReportErrors, GetReportResponses, GetStatusData, GetStatusResponses, GetTestData, GetTestErrors, GetTestResponses, ListTestsData, ListTestsErrors, ListTestsResponses, ReanalyzeReportData, ReanalyzeReportErrors, ReanalyzeReportResponses, TestDomainData, TestDomainErrors, TestDomainResponses, UploadEmlData, UploadEmlErrors, UploadEmlResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create a new deliverability test
 *
 * Generates a unique test email address for sending test emails. No database record is created until an email is received.
 */
export const createTest = <ThrowOnError extends boolean = false>(options?: Options<CreateTestData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateTestResponses, CreateTestErrors, ThrowOnError>({
        url: '/test',
        ...options
    });
};

/**
 * Analyze an uploaded EML file
 *
 * Analyzes a raw email message (.eml) provided by the user instead of one delivered to this instance's MTA. Authentication results are read from the Authentication-Results headers already present in the file, using an auto-detected authserv-id. The resulting report is stored like any other and is immediately available.
 *
 */
export const uploadEml = <ThrowOnError extends boolean = false>(options: Options<UploadEmlData, ThrowOnError>) => {
    return (options.client ?? client).post<UploadEmlResponses, UploadEmlErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/test/upload',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Get test status
 *
 * Check if a report exists for the given test ID (base32-encoded). Returns pending if no report exists, analyzed if a report is available.
 */
export const getTest = <ThrowOnError extends boolean = false>(options: Options<GetTestData, ThrowOnError>) => {
    return (options.client ?? client).get<GetTestResponses, GetTestErrors, ThrowOnError>({
        url: '/test/{id}',
        ...options
    });
};

/**
 * List all tests
 *
 * Returns a paginated list of test summaries with scores and grades. Can be disabled via server configuration.
 */
export const listTests = <ThrowOnError extends boolean = false>(options?: Options<ListTestsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListTestsResponses, ListTestsErrors, ThrowOnError>({
        url: '/tests',
        ...options
    });
};

/**
 * Get detailed report
 *
 * Retrieve comprehensive deliverability analysis report
 */
export const getReport = <ThrowOnError extends boolean = false>(options: Options<GetReportData, ThrowOnError>) => {
    return (options.client ?? client).get<GetReportResponses, GetReportErrors, ThrowOnError>({
        url: '/report/{id}',
        ...options
    });
};

/**
 * Get raw annotated email
 *
 * Retrieve the original email with headers added by filters
 */
export const getRawEmail = <ThrowOnError extends boolean = false>(options: Options<GetRawEmailData, ThrowOnError>) => {
    return (options.client ?? client).get<GetRawEmailResponses, GetRawEmailErrors, ThrowOnError>({
        url: '/report/{id}/raw.eml',
        ...options
    });
};

/**
 * Reanalyze email and regenerate report
 *
 * Re-run the analysis on the stored raw email to regenerate the report with the latest analyzer version. This is useful after analyzer improvements or bug fixes.
 */
export const reanalyzeReport = <ThrowOnError extends boolean = false>(options: Options<ReanalyzeReportData, ThrowOnError>) => {
    return (options.client ?? client).post<ReanalyzeReportResponses, ReanalyzeReportErrors, ThrowOnError>({
        url: '/report/{id}/reanalyze',
        ...options
    });
};

/**
 * Test a domain's email configuration
 *
 * Analyzes DNS records (MX, SPF, DMARC, BIMI) for a domain without requiring an actual email to be sent. Returns results immediately.
 */
export const testDomain = <ThrowOnError extends boolean = false>(options: Options<TestDomainData, ThrowOnError>) => {
    return (options.client ?? client).post<TestDomainResponses, TestDomainErrors, ThrowOnError>({
        url: '/domain',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Check a domain's BIMI record
 *
 * Looks up the BIMI Assertion Record of a domain and validates it together with the assets it points at (logo and Verified Mark Certificate), without requiring an actual email to be sent. The DMARC record of the same domain is reported alongside, since BIMI display depends on it. Returns results immediately.
 */
export const checkBimi = <ThrowOnError extends boolean = false>(options: Options<CheckBimiData, ThrowOnError>) => {
    return (options.client ?? client).post<CheckBimiResponses, CheckBimiErrors, ThrowOnError>({
        url: '/bimi',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Check an IP address against DNS blacklists
 *
 * Tests a single IP address (IPv4 or IPv6) against configured DNS-based blacklists (RBLs) without requiring an actual email to be sent. Returns results immediately.
 */
export const checkBlacklist = <ThrowOnError extends boolean = false>(options: Options<CheckBlacklistData, ThrowOnError>) => {
    return (options.client ?? client).post<CheckBlacklistResponses, CheckBlacklistErrors, ThrowOnError>({
        url: '/blacklist',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Service health check
 *
 * Get service health status and component versions
 */
export const getStatus = <ThrowOnError extends boolean = false>(options?: Options<GetStatusData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetStatusResponses, unknown, ThrowOnError>({
        url: '/status',
        ...options
    });
};
