// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/api' | 'https://api.example.com/api' | (string & {});
};

export type Test = SchemasTest;

export type TestResponse = SchemasTestResponse;

export type EmlUploadResponse = SchemasEmlUploadResponse;

export type Report = SchemasReport;

export type ScoreSummary = SchemasScoreSummary;

export type ContentAnalysis = SchemasContentAnalysis;

export type ContentIssue = SchemasContentIssue;

export type LinkCheck = SchemasLinkCheck;

export type ImageCheck = SchemasImageCheck;

export type HeaderAnalysis = SchemasHeaderAnalysis;

export type HeaderCheck = SchemasHeaderCheck;

export type ReceivedHop = SchemasReceivedHop;

export type DkimDomainInfo = SchemasDkimDomainInfo;

export type DomainAlignment = SchemasDomainAlignment;

export type HeaderIssue = SchemasHeaderIssue;

export type AuthenticationResults = SchemasAuthenticationResults;

export type AuthResult = SchemasAuthResult;

export type ArcResult = SchemasArcResult;

export type IpRevResult = SchemasIpRevResult;

export type SpamAssassinResult = SchemasSpamAssassinResult;

export type SpamTestDetail = SchemasSpamTestDetail;

export type RspamdResult = SchemasRspamdResult;

export type DnsResults = SchemasDnsResults;

export type MxRecord = SchemasMxRecord;

export type SpfRecord = SchemasSpfRecord;

export type DkimRecord = SchemasDkimRecord;

export type DmarcRecord = SchemasDmarcRecord;

export type BimiRecord = SchemasBimiRecord;

export type BimiCheck = SchemasBimiCheck;

export type VmcInfo = SchemasVmcInfo;

export type BlacklistCheck = SchemasBlacklistCheck;

export type Status = SchemasStatus;

export type _Error = SchemasError;

export type DomainTestRequest = SchemasDomainTestRequest;

export type DomainTestResponse = SchemasDomainTestResponse;

export type BimiCheckRequest = SchemasBimiCheckRequest;

export type BimiCheckResponse = SchemasBimiCheckResponse;

export type BlacklistCheckRequest = SchemasBlacklistCheckRequest;

export type BlacklistCheckResponse = SchemasBlacklistCheckResponse;

export type TestSummary = SchemasTestSummary;

export type TestListResponse = SchemasTestListResponse;

export type SchemasArcResult = {
    /**
     * Overall ARC chain validation result
     */
    result: 'pass' | 'fail' | 'none';
    /**
     * Whether the ARC chain signatures are valid
     */
    chain_valid?: boolean;
    /**
     * Number of ARC sets in the chain
     */
    chain_length?: number;
    /**
     * Additional details about ARC validation
     */
    details?: string;
};

export type SchemasAuthResult = {
    /**
     * Authentication result
     */
    result: 'pass' | 'fail' | 'invalid' | 'missing' | 'none' | 'neutral' | 'softfail' | 'temperror' | 'permerror' | 'declined' | 'domain_pass' | 'orgdomain_pass' | 'skipped';
    /**
     * Domain being authenticated
     */
    domain?: string;
    /**
     * DKIM selector (for DKIM only)
     */
    selector?: string;
    /**
     * SPF identity the result applies to (for SPF only): the envelope sender (smtp.mailfrom) or the HELO/EHLO name (smtp.helo).
     */
    identity?: 'mailfrom' | 'helo';
    /**
     * Additional details about the result
     */
    details?: string;
};

export type SchemasAuthenticationResults = {
    /**
     * SPF result for the envelope sender (smtp.mailfrom). This is the result that authenticates the sender and feeds DMARC alignment.
     */
    spf?: SchemasAuthResult;
    /**
     * SPF result for the HELO/EHLO identity (smtp.helo), when the receiver reports it alongside the envelope sender check. Informational: only `spf` authenticates the sender for DMARC purposes.
     */
    spf_helo?: SchemasAuthResult;
    dkim?: Array<SchemasAuthResult>;
    dmarc?: SchemasAuthResult;
    bimi?: SchemasAuthResult;
    arc?: SchemasArcResult;
    iprev?: SchemasIpRevResult;
    x_google_dkim?: SchemasAuthResult;
    x_aligned_from?: SchemasAuthResult;
    x_ptr?: SchemasXPtrResult;
    x_tls?: SchemasAuthResult;
};

export type SchemasBimiCheck = {
    /**
     * Machine-readable check identifier
     */
    name: string;
    /**
     * Human-readable check title
     */
    description: string;
    /**
     * Check outcome
     */
    status: 'pass' | 'fail' | 'warning' | 'skipped';
    /**
     * Reasons explaining a failure or warning, each tagged with its own severity
     */
    messages?: Array<SchemasBimiCheckMessage>;
};

export type SchemasBimiCheckMessage = {
    /**
     * Human-readable explanation
     */
    text: string;
    /**
     * Severity of this specific message. A "fail" check can carry both error and warning messages; only the error ones caused the failure. A check that did not fail carries informational messages, explaining why it was skipped or what it observed.
     */
    severity: 'error' | 'warning' | 'info';
};

export type SchemasBimiCheckRequest = {
    /**
     * Domain name whose BIMI record is looked up (e.g., example.com)
     */
    domain: string;
    /**
     * Selector the record is published under. Defaults to `default`, the selector a message that carries no `BIMI-Selector` header is served.
     */
    selector?: string;
    /**
     * Local-part of a sending address, so discovery can follow the `lps=` tag of a record that serves one Indicator per mailbox. Omit to report the Indicator the selector alone leads to.
     */
    local_part?: string;
};

export type SchemasBimiCheckResponse = {
    /**
     * The domain that was checked
     */
    domain: string;
    /**
     * The selector the lookup started from, before any local-part redirection
     */
    selector: string;
    /**
     * The local-part discovery was run for, when one was supplied
     */
    local_part?: string;
    bimi_record: SchemasBimiRecord;
    dmarc_record?: SchemasDmarcRecord;
};

export type SchemasBimiRecord = {
    /**
     * BIMI selector the record was found under. Equal to `requested_selector`, or a selector derived from the sender's local-part when the record published at the requested selector redirected discovery through its `lps=` tag.
     */
    selector: string;
    /**
     * Selector the lookup started from, before any local-part selector redirection.
     */
    requested_selector?: string;
    /**
     * Domain name the BIMI record was requested for
     */
    domain: string;
    /**
     * Domain the record was actually found at. Equal to `domain`, or its organizational domain when the queried domain publishes no BIMI record of its own and inherits the one published there.
     */
    record_domain?: string;
    /**
     * BIMI record content
     */
    record?: string;
    /**
     * URL to the brand logo (SVG)
     */
    logo_url?: string;
    /**
     * URL to Verified Mark Certificate (optional)
     */
    vmc_url?: string;
    /**
     * Whether the record publishes an `lps=` tag, sending some senders to a selector named after their address so they can be served another Indicator than this one. Absent when the tag is not published.
     */
    local_part_selector?: boolean;
    /**
     * Local-part prefixes listed by the `lps=` tag. Present but empty when the tag is published without a value, which means every local-part is sent to its own selector.
     */
    local_part_prefixes?: Array<string>;
    /**
     * Value published in the `avp=` tag, telling providers that display personal avatars whether to prefer the sender's avatar or the brand Indicator. Absent when the tag is not published, in which case `brand` applies.
     */
    avatar_preference?: string;
    /**
     * Whether the DNS TXT record itself is syntactically valid (well-formed BIMI record). This can be true even when `valid` is false because the referenced assets (logo, VMC) failed validation.
     */
    record_valid?: boolean;
    /**
     * Whether the BIMI record and its referenced assets (logo, VMC) are fully compliant
     */
    valid: boolean;
    /**
     * Error message if validation failed
     */
    error?: string;
    /**
     * Detailed validation checks performed on the BIMI assets (logo and certificate)
     */
    checks?: Array<SchemasBimiCheck>;
    vmc?: SchemasVmcInfo;
};

export type SchemasBlacklistCheck = {
    /**
     * RBL/DNSBL name
     */
    rbl: string;
    /**
     * Whether IP is listed
     */
    listed: boolean;
    /**
     * RBL response code or message
     */
    response?: string;
    /**
     * RBL error if any
     */
    error?: string;
};

export type SchemasBlacklistCheckRequest = {
    /**
     * IPv4 or IPv6 address to check against blacklists
     */
    ip: string;
};

export type SchemasBlacklistCheckResponse = {
    /**
     * The IP address that was checked
     */
    ip: string;
    /**
     * List of blacklist check results
     */
    blacklists: Array<SchemasBlacklistCheck>;
    /**
     * Number of blacklists that have this IP listed
     */
    listed_count: number;
    /**
     * Blacklist score (0-100, higher is better)
     */
    score: number;
    /**
     * Letter grade representation of the score
     */
    grade: 'A+' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
    /**
     * List of DNS whitelist check results (informational only)
     */
    whitelists?: Array<SchemasBlacklistCheck>;
};

export type SchemasContentAnalysis = {
    /**
     * Whether email contains HTML part
     */
    has_html?: boolean;
    /**
     * Whether email contains plaintext part
     */
    has_plaintext?: boolean;
    /**
     * Issues found in HTML content
     */
    html_issues?: Array<SchemasContentIssue>;
    /**
     * Analysis of links found in the email
     */
    links?: Array<SchemasLinkCheck>;
    /**
     * Analysis of images in the email
     */
    images?: Array<SchemasImageCheck>;
    /**
     * Ratio of text to images (higher is better)
     */
    text_to_image_ratio?: number;
    /**
     * Whether email contains an unsubscribe link
     */
    has_unsubscribe_link?: boolean;
    /**
     * Available unsubscribe methods
     */
    unsubscribe_methods?: Array<'link' | 'mailto' | 'list-unsubscribe-header' | 'one-click'>;
};

export type SchemasContentIssue = {
    /**
     * Type of content issue
     */
    type: 'broken_html' | 'missing_alt' | 'excessive_images' | 'obfuscated_url' | 'suspicious_link' | 'dangerous_html' | 'unreplaced_template' | 'truncated_body';
    /**
     * Issue severity
     */
    severity: 'critical' | 'high' | 'medium' | 'low' | 'info';
    /**
     * Human-readable description
     */
    message: string;
    /**
     * Where the issue was found
     */
    location?: string;
    /**
     * How to fix this issue
     */
    advice?: string;
};

export type SchemasDkimDomainInfo = {
    /**
     * DKIM signature domain
     */
    domain: string;
    /**
     * Organizational domain extracted from DKIM domain (using Public Suffix List)
     */
    org_domain: string;
};

export type SchemasDkimRecord = {
    /**
     * DKIM selector
     */
    selector: string;
    /**
     * Domain name
     */
    domain: string;
    /**
     * DKIM record content
     */
    record?: string;
    /**
     * Key type from k= tag (e.g. rsa, ed25519); defaults to rsa if absent
     */
    key_type?: string;
    /**
     * Acceptable hash algorithms from h= tag; empty means all accepted (RFC 6376 default: sha256)
     */
    hash_algorithms?: Array<string>;
    /**
     * Algorithm used in DKIM-Signature a= tag (e.g. rsa-sha256, ed25519-sha256)
     */
    signing_algorithm?: string;
    /**
     * Public key size in bits (RSA: 1024/2048/4096; Ed25519: always 256)
     */
    key_size?: number;
    /**
     * Whether the DKIM record is valid
     */
    valid: boolean;
    /**
     * Error message if validation failed
     */
    error?: string;
};

export type SchemasDmarcRecord = {
    /**
     * DMARC record content
     */
    record?: string;
    /**
     * Domain at which the DMARC record was found (may differ from From domain when organizational domain fallback was used)
     */
    domain?: string;
    /**
     * DMARC policy
     */
    policy?: 'none' | 'quarantine' | 'reject' | 'unknown';
    /**
     * DMARC subdomain policy (sp tag) - policy for subdomains if different from main policy
     */
    subdomain_policy?: 'none' | 'quarantine' | 'reject' | 'unknown';
    /**
     * DMARC non-existent subdomain policy (np tag) - policy for non-existent subdomains (NXDOMAIN); defaults to sp= or p= if absent (DMARCbis)
     */
    nonexistent_subdomain_policy?: 'none' | 'quarantine' | 'reject' | 'unknown';
    /**
     * Percentage of messages subjected to filtering (pct tag, default 100). DEPRECATED in DMARCbis: use test_mode (t=y) instead.
     */
    percentage?: number;
    /**
     * DMARCbis t= tag: when true (t=y), receivers downgrade effective policy one level (reject→quarantine, quarantine→none). Replaces the deprecated pct= tag for testing.
     */
    test_mode?: boolean;
    /**
     * DMARCbis psd= tag: y=this is a Public Suffix Domain, n=this is an Organizational Domain boundary, u=unknown (default, use DNS Tree Walk to determine)
     */
    psd?: 'y' | 'n' | 'u';
    /**
     * Whether the deprecated pct= tag was found in the record (pct is removed in DMARCbis; migrate to t=y for testing mode)
     */
    deprecated_pct?: boolean;
    /**
     * Whether the deprecated rf= tag was found in the record (rf is removed in DMARCbis; failure report formats are now defined separately)
     */
    deprecated_rf?: boolean;
    /**
     * Whether the deprecated ri= tag was found in the record (ri is removed in DMARCbis; aggregate reporting interval is now fixed at ≥24 hours)
     */
    deprecated_ri?: boolean;
    /**
     * SPF alignment mode (aspf tag)
     */
    spf_alignment?: 'relaxed' | 'strict';
    /**
     * DKIM alignment mode (adkim tag)
     */
    dkim_alignment?: 'relaxed' | 'strict';
    /**
     * Whether the DMARC record is valid
     */
    valid: boolean;
    /**
     * Error message if validation failed
     */
    error?: string;
};

export type SchemasDnsResults = {
    /**
     * From Domain name
     */
    from_domain: string;
    /**
     * Return Path Domain name
     */
    rp_domain?: string;
    /**
     * MX records for the From domain
     */
    from_mx_records?: Array<SchemasMxRecord>;
    /**
     * MX records for the Return-Path domain
     */
    rp_mx_records?: Array<SchemasMxRecord>;
    /**
     * SPF records found (includes resolved include directives)
     */
    spf_records?: Array<SchemasSpfRecord>;
    /**
     * DKIM records found
     */
    dkim_records?: Array<SchemasDkimRecord>;
    dmarc_record?: SchemasDmarcRecord;
    bimi_record?: SchemasBimiRecord;
    /**
     * Sender IP address used for PTR/FCrDNS verification, taken from the hop the received chain marks as inbound
     */
    sender_ip?: string;
    /**
     * PTR (reverse DNS) records for the sender IP address
     */
    ptr_records?: Array<string>;
    /**
     * A or AAAA records resolved from the PTR hostnames (forward confirmation)
     */
    ptr_forward_records?: Array<string>;
    /**
     * HELO/EHLO hostname announced by the sending server (from the inbound Received hop)
     */
    helo_hostname?: string;
    /**
     * Whether the announced HELO hostname matches one of the sender's PTR records (case-insensitive)
     */
    helo_ptr_match?: boolean;
    /**
     * SPF record published for the announced HELO/EHLO hostname. Informational only: publishing one lets receivers authenticate the HELO identity, but its absence is a recommendation rather than an error and never affects any score.
     */
    helo_spf_record?: SchemasSpfRecord;
    return_ok?: SchemasReturnOk;
    /**
     * DNS lookup errors
     */
    errors?: Array<string>;
};

export type SchemasDomainAlignment = {
    /**
     * Domain from From header
     */
    from_domain?: string;
    /**
     * Organizational domain extracted from From header (using Public Suffix List)
     */
    from_org_domain?: string;
    /**
     * Domain from Return-Path header
     */
    return_path_domain?: string;
    /**
     * Organizational domain extracted from Return-Path header (using Public Suffix List)
     */
    return_path_org_domain?: string;
    /**
     * Domains from DKIM signatures with their organizational domains
     */
    dkim_domains?: Array<SchemasDkimDomainInfo>;
    /**
     * Whether all domains align (strict alignment - exact match)
     */
    aligned?: boolean;
    /**
     * Whether domains satisfy relaxed alignment (organizational domain match)
     */
    relaxed_aligned?: boolean;
    /**
     * Alignment issues
     */
    issues?: Array<string>;
};

export type SchemasDomainTestRequest = {
    /**
     * Domain name to test (e.g., example.com)
     */
    domain: string;
};

export type SchemasDomainTestResponse = {
    /**
     * The tested domain name
     */
    domain: string;
    /**
     * Overall domain configuration score (0-100)
     */
    score: number;
    /**
     * Letter grade representation of the score
     */
    grade: 'A+' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
    dns_results: SchemasDnsResults;
    /**
     * Whether the domain is a known disposable email provider
     */
    is_disposable?: boolean;
};

export type SchemasEmlUploadResponse = {
    /**
     * Identifier of the test created for this upload (base32-encoded with hyphens)
     */
    id: string;
    /**
     * Uploads are analyzed synchronously, so the report is immediately available
     */
    status: 'analyzed';
    source: 'uploaded';
};

export type SchemasError = {
    /**
     * Error code
     */
    error: string;
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * Additional error details
     */
    details?: string;
};

export type SchemasHeaderAnalysis = {
    /**
     * Whether body has a MIME structure
     */
    has_mime_structure?: boolean;
    /**
     * Map of header names to their check results (e.g., "from", "to", "dkim-signature")
     */
    headers?: {
        [key: string]: SchemasHeaderCheck;
    };
    /**
     * Chain of Received headers showing email path
     */
    received_chain?: Array<SchemasReceivedHop>;
    domain_alignment?: SchemasDomainAlignment;
    /**
     * Issues found in headers
     */
    issues?: Array<SchemasHeaderIssue>;
};

export type SchemasHeaderCheck = {
    /**
     * Whether the header is present
     */
    present: boolean;
    /**
     * Header value
     */
    value?: string;
    /**
     * Whether the value is valid/well-formed
     */
    valid?: boolean;
    /**
     * How important this header is for deliverability
     */
    importance?: 'required' | 'recommended' | 'optional' | 'newsletter';
    /**
     * Any issues with this header
     */
    issues?: Array<string>;
};

export type SchemasHeaderIssue = {
    /**
     * Header name
     */
    header: string;
    /**
     * Issue severity
     */
    severity: 'critical' | 'high' | 'medium' | 'low' | 'info';
    /**
     * Human-readable description
     */
    message: string;
    /**
     * How to fix this issue
     */
    advice?: string;
};

export type SchemasIpRevResult = {
    /**
     * IP reverse DNS lookup result
     */
    result: 'pass' | 'fail' | 'temperror' | 'permerror';
    /**
     * IP address that was checked
     */
    ip?: string;
    /**
     * Hostname from reverse DNS lookup (PTR record)
     */
    hostname?: string;
    /**
     * Additional details about the IP reverse lookup
     */
    details?: string;
};

export type SchemasImageCheck = {
    /**
     * Image source URL or path
     */
    src?: string;
    /**
     * Whether image has alt attribute
     */
    has_alt: boolean;
    /**
     * Alt text content
     */
    alt_text?: string;
    /**
     * Whether this appears to be a tracking pixel (1x1 image)
     */
    is_tracking_pixel?: boolean;
};

export type SchemasLinkCheck = {
    /**
     * The URL found in the email
     */
    url: string;
    /**
     * Link validation status
     */
    status: 'valid' | 'broken' | 'suspicious' | 'redirected' | 'timeout';
    /**
     * HTTP status code received
     */
    http_code?: number;
    /**
     * URLs in the redirect chain, if any
     */
    redirect_chain?: Array<string>;
    /**
     * Whether this is a URL shortener
     */
    is_shortened?: boolean;
};

export type SchemasMxRecord = {
    /**
     * MX hostname
     */
    host: string;
    /**
     * MX priority (lower is higher priority)
     */
    priority: number;
    /**
     * Whether the MX record is valid
     */
    valid: boolean;
    /**
     * Error message if validation failed
     */
    error?: string;
};

export type SchemasReceivedHop = {
    /**
     * Sending server hostname
     */
    from?: string;
    /**
     * Receiving server hostname
     */
    by?: string;
    /**
     * Protocol used
     */
    with?: string;
    /**
     * Message ID at this hop
     */
    id?: string;
    /**
     * When this hop occurred
     */
    timestamp?: string;
    /**
     * IP address of the sending server (IPv4 or IPv6)
     */
    ip?: string;
    /**
     * Reverse DNS (PTR record) for the IP address
     */
    reverse?: string;
    tls?: SchemasTlsInfo;
    /**
     * Whether the message entered the recipient's infrastructure through this hop, the one the sender IP, the HELO name and the PTR check are taken from. Set on at most one hop; the hops above it are the recipient's own, not the sender's.
     */
    inbound?: boolean;
};

export type SchemasReport = {
    /**
     * Report identifier (base32-encoded with hyphens)
     */
    id: string;
    /**
     * Associated test ID (base32-encoded with hyphens)
     */
    test_id: string;
    /**
     * Overall deliverability score as percentage (0-100)
     */
    score: number;
    /**
     * Letter grade representation of the score (A+ is best, F is worst)
     */
    grade: 'A+' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
    summary?: SchemasScoreSummary;
    authentication?: SchemasAuthenticationResults;
    spamassassin?: SchemasSpamAssassinResult;
    rspamd?: SchemasRspamdResult;
    dns_results?: SchemasDnsResults;
    /**
     * Map of IP addresses to their blacklist check results (array of checks per IP)
     */
    blacklists?: {
        [key: string]: Array<SchemasBlacklistCheck>;
    };
    /**
     * Map of IP addresses to their DNS whitelist check results (informational only)
     */
    whitelists?: {
        [key: string]: Array<SchemasBlacklistCheck>;
    };
    content_analysis?: SchemasContentAnalysis;
    header_analysis?: SchemasHeaderAnalysis;
    /**
     * Raw email headers
     */
    raw_headers?: string;
    /**
     * Where the analyzed message comes from. `received` means it was delivered to this instance's MTA, which produced the Authentication-Results headers itself. `uploaded` means the user provided an .eml file: authentication verdicts then come from whichever server originally handled the message, and missing verdicts do not indicate a misconfiguration of this instance. Absent on reports generated before this field existed, which are all `received`.
     *
     */
    source?: 'received' | 'uploaded';
    /**
     * authserv-id of the Authentication-Results headers that were trusted for this report. For `received` reports this is the configured receiver hostname; for `uploaded` reports it is auto-detected from the file.
     *
     */
    authserv_id?: string;
    /**
     * Every authserv-id found in the message's Authentication-Results headers, most recent first (informational)
     */
    authserv_ids_found?: Array<string>;
    created_at: string;
};

/**
 * Whether the sender domains can receive replies and bounces (MX, with A/AAAA fallback)
 */
export type SchemasReturnOk = {
    from?: SchemasReturnOkDomain;
    return_path?: SchemasReturnOkDomain;
};

export type SchemasReturnOkDomain = {
    /**
     * Domain that was evaluated
     */
    domain: string;
    /**
     * pass = MX present, warn = only A/AAAA records (implicit MX), fail = no records
     */
    status: 'pass' | 'warn' | 'fail';
    /**
     * Whether the domain has at least one MX record
     */
    has_mx?: boolean;
    /**
     * Whether the domain has an A or AAAA record (implicit MX fallback)
     */
    has_address?: boolean;
    /**
     * Organizational domain used as fallback when the domain itself had no records
     */
    org_domain?: string;
};

export type SchemasRspamdResult = {
    /**
     * rspamd deliverability score (0-100, higher is better)
     */
    deliverability_score?: number;
    /**
     * Letter grade for rspamd deliverability score
     */
    deliverability_grade?: 'A+' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
    /**
     * rspamd spam score
     */
    score: number;
    /**
     * Score at which the instance rejects a message, as rspamd reported it for this one. Absent when rspamd reported none: is_spam is then computed against rspamd's own default, which a client is not expected to know. Also absent on reports stored before this field existed.
     */
    threshold?: number;
    /**
     * rspamd action (no action, add header, rewrite subject, soft reject, reject)
     */
    action?: string;
    /**
     * Whether message is classified as spam (action is reject or soft reject)
     */
    is_spam: boolean;
    /**
     * rspamd server that processed the message
     */
    server?: string;
    /**
     * Map of triggered rspamd symbols to their details
     */
    symbols: {
        [key: string]: SchemasSpamTestDetail;
    };
    /**
     * Full rspamd report (raw X-Spamd-Result header)
     */
    report?: string;
};

export type SchemasSpfRecord = {
    /**
     * Domain this SPF record belongs to
     */
    domain?: string;
    /**
     * SPF record content
     */
    record?: string;
    /**
     * Whether the SPF record is valid
     */
    valid: boolean;
    /**
     * Qualifier for the 'all' mechanism: + (pass), - (fail), ~ (softfail), ? (neutral)
     */
    all_qualifier?: '+' | '-' | '~' | '?';
    /**
     * Error message if validation failed
     */
    error?: string;
};

export type SchemasScoreSummary = {
    /**
     * DNS records score (in percentage)
     */
    dns_score: number;
    /**
     * Letter grade representation of the score (A+ is best, F is worst)
     */
    dns_grade: 'A+' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
    /**
     * SPF/DKIM/DMARC score (in percentage)
     */
    authentication_score: number;
    /**
     * Letter grade representation of the score (A+ is best, F is worst)
     */
    authentication_grade: 'A+' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
    /**
     * Spam filter score (SpamAssassin + rspamd combined, in percentage)
     */
    spam_score: number;
    /**
     * Letter grade representation of the score (A+ is best, F is worst)
     */
    spam_grade: 'A+' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
    /**
     * Blacklist check score (in percentage)
     */
    blacklist_score: number;
    /**
     * Letter grade representation of the score (A+ is best, F is worst)
     */
    blacklist_grade: 'A+' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
    /**
     * Header quality score (in percentage)
     */
    header_score: number;
    /**
     * Letter grade representation of the score (A+ is best, F is worst)
     */
    header_grade: 'A+' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
    /**
     * Content quality score (in percentage)
     */
    content_score: number;
    /**
     * Letter grade representation of the score (A+ is best, F is worst)
     */
    content_grade: 'A+' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
};

export type SchemasSpamAssassinResult = {
    /**
     * SpamAssassin deliverability score (0-100, higher is better)
     */
    deliverability_score?: number;
    /**
     * Letter grade for SpamAssassin deliverability score
     */
    deliverability_grade?: 'A+' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
    /**
     * SpamAssassin version
     */
    version?: string;
    /**
     * SpamAssassin spam score
     */
    score: number;
    /**
     * Threshold for spam classification
     */
    required_score: number;
    /**
     * Whether message is classified as spam
     */
    is_spam: boolean;
    /**
     * List of triggered SpamAssassin tests
     */
    tests?: Array<string>;
    /**
     * Map of test names to their detailed results
     */
    test_details: {
        [key: string]: SchemasSpamTestDetail;
    };
    /**
     * Full SpamAssassin report
     */
    report?: string;
};

export type SchemasSpamTestDetail = {
    /**
     * Test name
     */
    name: string;
    /**
     * Score contribution of this test
     */
    score: number;
    /**
     * Symbol parameters or options
     */
    params?: string;
    /**
     * Human-readable description of what this test checks
     */
    description?: string;
};

export type SchemasStatus = {
    /**
     * Overall service status
     */
    status: 'healthy' | 'degraded' | 'unhealthy';
    /**
     * Service version
     */
    version: string;
    components?: {
        database?: 'up' | 'down';
        mta?: 'up' | 'down';
    };
    /**
     * Service uptime in seconds
     */
    uptime?: number;
};

export type SchemasTlsInfo = {
    /**
     * TLS protocol version
     */
    version?: string;
    /**
     * Cipher suite used
     */
    cipher?: string;
    /**
     * Cipher strength in bits
     */
    bits?: number;
    /**
     * Whether the peer certificate was verified/trusted
     */
    verified?: boolean;
};

export type SchemasTest = {
    /**
     * Unique test identifier (base32-encoded with hyphens)
     */
    id: string;
    /**
     * Unique test email address
     */
    email: string;
    /**
     * Current test status (pending = no report yet, analyzed = report available)
     */
    status: 'pending' | 'analyzed';
};

export type SchemasTestListResponse = {
    tests: Array<SchemasTestSummary>;
    /**
     * Total number of tests
     */
    total: number;
    /**
     * Current offset
     */
    offset: number;
    /**
     * Current limit
     */
    limit: number;
};

export type SchemasTestResponse = {
    /**
     * Unique test identifier (base32-encoded with hyphens)
     */
    id: string;
    email: string;
    status: 'pending';
    message?: string;
};

export type SchemasTestSummary = {
    /**
     * Test identifier (base32-encoded with hyphens)
     */
    test_id: string;
    /**
     * Overall deliverability score (0-100)
     */
    score: number;
    /**
     * Letter grade
     */
    grade: 'A+' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
    /**
     * Sender domain extracted from the report
     */
    from_domain?: string;
    /**
     * Where the analyzed message came from (absent on reports predating this field, which are all `received`)
     */
    source?: 'received' | 'uploaded';
    created_at: string;
};

export type SchemasVmcInfo = {
    /**
     * Issuer of the leaf certificate
     */
    issuer?: string;
    /**
     * Subject of the leaf certificate
     */
    subject?: string;
    /**
     * Serial number of the leaf certificate
     */
    serial_number?: string;
    /**
     * Start of the certificate validity period
     */
    not_before?: string;
    /**
     * End of the certificate validity period
     */
    not_after?: string;
    /**
     * DNS names listed in the Subject Alternative Name extension
     */
    san_domains?: Array<string>;
    /**
     * Whether the certificate carries the BIMI Extended Key Usage (1.3.6.1.5.5.7.3.31)
     */
    has_bimi_eku?: boolean;
    /**
     * Whether the certificate of the immediate issuer carries the BIMI Extended Key Usage too, as the profile requires of it. Absent when the chain does not carry that certificate.
     */
    issuer_has_bimi_eku?: boolean;
    /**
     * Whether the certificate carries the logotype extension (1.3.6.1.5.5.7.1.12)
     */
    has_logotype?: boolean;
    /**
     * Whether the logo embedded in the certificate matches the logotypeHash the authority computed over it, which binds the mark to the certificate. Absent when no hash could be checked.
     */
    logo_hash_verified?: boolean;
    /**
     * Digest the logotypeHash was verified with. Absent when no verification took place.
     */
    logo_hash_algorithm?: string;
    /**
     * Media type the certificate carries its mark under. Absent when the logotype extension could not be read.
     */
    logo_media_type?: string;
    /**
     * Whether the certificate publishes where its revocation status can be checked (cRLDistributionPoints)
     */
    has_crl_distribution_points?: boolean;
    /**
     * Number of Signed Certificate Timestamps embedded in the certificate, proving it was logged to Certificate Transparency logs. Absent when the extension could not be read.
     */
    sct_count?: number;
    /**
     * Whether the issuance chain leads to a trusted BIMI root certificate. Absent when no set of trusted roots was supplied, in which case nothing is claimed about the issuer's legitimacy.
     */
    chain_trusted?: boolean;
    /**
     * Whether the SVG embedded in the certificate matches the logo published at the l= URL
     */
    logo_matches?: boolean;
    /**
     * Number of certificates provided in the PEM chain
     */
    chain_length?: number;
    /**
     * Whether the VMC passed all analysed criteria
     */
    valid: boolean;
    /**
     * Error message if the VMC could not be analysed
     */
    error?: string;
};

export type SchemasXPtrResult = {
    /**
     * HELO/PTR consistency check result
     */
    result: 'pass' | 'fail' | 'none' | 'temperror' | 'permerror';
    /**
     * HELO/EHLO hostname announced by the sending server (smtp.helo)
     */
    helo?: string;
    /**
     * Reverse DNS (PTR) hostname of the sender IP (policy.ptr)
     */
    ptr?: string;
    /**
     * Additional details about the x-ptr check
     */
    details?: string;
};

export type CreateTestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test';
};

export type CreateTestErrors = {
    /**
     * Internal server error
     */
    500: SchemasError;
};

export type CreateTestError = CreateTestErrors[keyof CreateTestErrors];

export type CreateTestResponses = {
    /**
     * Test email address generated successfully
     */
    201: SchemasTestResponse;
};

export type CreateTestResponse = CreateTestResponses[keyof CreateTestResponses];

export type UploadEmlData = {
    body: {
        /**
         * The raw email message to analyze
         */
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/test/upload';
};

export type UploadEmlErrors = {
    /**
     * Missing, oversized or unparsable file
     */
    400: SchemasError;
    /**
     * EML upload is disabled on this instance
     */
    403: SchemasError;
    /**
     * Internal server error
     */
    500: SchemasError;
};

export type UploadEmlError = UploadEmlErrors[keyof UploadEmlErrors];

export type UploadEmlResponses = {
    /**
     * File analyzed successfully
     */
    201: SchemasEmlUploadResponse;
};

export type UploadEmlResponse = UploadEmlResponses[keyof UploadEmlResponses];

export type GetTestData = {
    body?: never;
    path: {
        /**
         * Base32-encoded test ID (with hyphens)
         */
        id: string;
    };
    query?: never;
    url: '/test/{id}';
};

export type GetTestErrors = {
    /**
     * Internal server error
     */
    500: SchemasError;
};

export type GetTestError = GetTestErrors[keyof GetTestErrors];

export type GetTestResponses = {
    /**
     * Test status retrieved successfully
     */
    200: SchemasTest;
};

export type GetTestResponse = GetTestResponses[keyof GetTestResponses];

export type ListTestsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of items to skip
         */
        offset?: number;
        /**
         * Maximum number of items to return
         */
        limit?: number;
    };
    url: '/tests';
};

export type ListTestsErrors = {
    /**
     * Test listing is disabled
     */
    403: SchemasError;
    /**
     * Internal server error
     */
    500: SchemasError;
};

export type ListTestsError = ListTestsErrors[keyof ListTestsErrors];

export type ListTestsResponses = {
    /**
     * List of test summaries
     */
    200: SchemasTestListResponse;
};

export type ListTestsResponse = ListTestsResponses[keyof ListTestsResponses];

export type GetReportData = {
    body?: never;
    path: {
        /**
         * Base32-encoded test ID (with hyphens)
         */
        id: string;
    };
    query?: never;
    url: '/report/{id}';
};

export type GetReportErrors = {
    /**
     * Report not found
     */
    404: SchemasError;
};

export type GetReportError = GetReportErrors[keyof GetReportErrors];

export type GetReportResponses = {
    /**
     * Report retrieved successfully
     */
    200: SchemasReport;
};

export type GetReportResponse = GetReportResponses[keyof GetReportResponses];

export type GetRawEmailData = {
    body?: never;
    path: {
        /**
         * Base32-encoded test ID (with hyphens)
         */
        id: string;
    };
    query?: never;
    url: '/report/{id}/raw.eml';
};

export type GetRawEmailErrors = {
    /**
     * Email not found
     */
    404: SchemasError;
};

export type GetRawEmailError = GetRawEmailErrors[keyof GetRawEmailErrors];

export type GetRawEmailResponses = {
    /**
     * Raw email retrieved successfully
     */
    200: string;
};

export type GetRawEmailResponse = GetRawEmailResponses[keyof GetRawEmailResponses];

export type ReanalyzeReportData = {
    body?: never;
    path: {
        /**
         * Base32-encoded test ID (with hyphens)
         */
        id: string;
    };
    query?: never;
    url: '/report/{id}/reanalyze';
};

export type ReanalyzeReportErrors = {
    /**
     * Email not found
     */
    404: SchemasError;
    /**
     * Internal server error during reanalysis
     */
    500: SchemasError;
};

export type ReanalyzeReportError = ReanalyzeReportErrors[keyof ReanalyzeReportErrors];

export type ReanalyzeReportResponses = {
    /**
     * Report regenerated successfully
     */
    200: SchemasReport;
};

export type ReanalyzeReportResponse = ReanalyzeReportResponses[keyof ReanalyzeReportResponses];

export type TestDomainData = {
    body: SchemasDomainTestRequest;
    path?: never;
    query?: never;
    url: '/domain';
};

export type TestDomainErrors = {
    /**
     * Invalid request
     */
    400: SchemasError;
    /**
     * Internal server error
     */
    500: SchemasError;
};

export type TestDomainError = TestDomainErrors[keyof TestDomainErrors];

export type TestDomainResponses = {
    /**
     * Domain test completed successfully
     */
    200: SchemasDomainTestResponse;
};

export type TestDomainResponse = TestDomainResponses[keyof TestDomainResponses];

export type CheckBimiData = {
    body: SchemasBimiCheckRequest;
    path?: never;
    query?: never;
    url: '/bimi';
};

export type CheckBimiErrors = {
    /**
     * Invalid request
     */
    400: SchemasError;
    /**
     * Internal server error
     */
    500: SchemasError;
};

export type CheckBimiError = CheckBimiErrors[keyof CheckBimiErrors];

export type CheckBimiResponses = {
    /**
     * BIMI check completed successfully
     */
    200: SchemasBimiCheckResponse;
};

export type CheckBimiResponse = CheckBimiResponses[keyof CheckBimiResponses];

export type CheckBlacklistData = {
    body: SchemasBlacklistCheckRequest;
    path?: never;
    query?: never;
    url: '/blacklist';
};

export type CheckBlacklistErrors = {
    /**
     * Invalid request
     */
    400: SchemasError;
    /**
     * Internal server error
     */
    500: SchemasError;
};

export type CheckBlacklistError = CheckBlacklistErrors[keyof CheckBlacklistErrors];

export type CheckBlacklistResponses = {
    /**
     * Blacklist check completed successfully
     */
    200: SchemasBlacklistCheckResponse;
};

export type CheckBlacklistResponse = CheckBlacklistResponses[keyof CheckBlacklistResponses];

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type GetStatusResponses = {
    /**
     * Service status
     */
    200: SchemasStatus;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];
